export const planetInfo = {
  sun: `🌞 <b>Sun</b><br>Type: Yellow Dwarf<br>Diameter: 1,391,000 km<br>Mass: 333,000× Earth<br>Temperature: 5,500°C (surface) / 15,000,000°C (core)<br>Age: 4.6 billion years<br>Fact: Contains 99.8% of the solar system's mass.`,
  mercury: `🪐 <b>Mercury</b><br>Diameter: 4,879 km<br>Orbit Speed: 47.87 km/s<br>Distance: 58M km<br>Moons: 0<br>Gravity: 3.7 m/s²<br>Length of Day: 58.6 Earth days<br>Length of Year: 88 Earth days<br>Atmosphere: Trace exosphere (Hydrogen, Helium, Oxygen, Sodium)<br>Avg. Temp: -173°C to 427°C<br>Fact: No atmosphere — extreme temperature variations.`,
  venus: `🪐 <b>Venus</b><br>Diameter: 12,104 km<br>Orbit Speed: 35.02 km/s<br>Distance: 108M km<br>Moons: 0<br>Gravity: 8.87 m/s²<br>Length of Day: 243 Earth days (retrograde)<br>Length of Year: 225 Earth days<br>Atmosphere: CO₂ (96.5%), Nitrogen (3.5%)<br>Avg. Temp: 462°C<br>Fact: Hottest planet due to runaway greenhouse effect.`,
  earth: `🌍 <b>Earth</b><br>Diameter: 12,742 km<br>Orbit Speed: 29.78 km/s<br>Distance: 150M km<br>Moons: 1<br>Gravity: 9.8 m/s²<br>Length of Day: 24 hours<br>Length of Year: 365 days<br>Atmosphere: Nitrogen (78%), Oxygen (21%)<br>Avg. Temp: 15°C<br>Fact: Only planet known to support life.`,
  mars: `🔴 <b>Mars</b><br>Diameter: 6,779 km<br>Orbit Speed: 24.07 km/s<br>Distance: 228M km<br>Moons: 2<br>Gravity: 3.72 m/s²<br>Length of Day: 24.6 hours<br>Length of Year: 687 Earth days<br>Atmosphere: CO₂ (95%), Nitrogen, Argon<br>Avg. Temp: -63°C<br>Fact: Olympus Mons is the tallest volcano in the Solar System.`,
  jupiter: `🟠 <b>Jupiter</b><br>Diameter: 139,820 km<br>Orbit Speed: 13.07 km/s<br>Distance: 778M km<br>Moons: 95<br>Gravity: 24.79 m/s²<br>Length of Day: 9.9 hours<br>Length of Year: 11.86 years<br>Atmosphere: Hydrogen (90%), Helium (10%)<br>Avg. Temp: -145°C<br>Fact: Largest planet with a giant red storm.`,
  saturn: `🪐 <b>Saturn</b><br>Diameter: 116,460 km<br>Orbit Speed: 9.68 km/s<br>Distance: 1.43B km<br>Moons: 146<br>Gravity: 10.44 m/s²<br>Length of Day: 10.7 hours<br>Length of Year: 29.45 years<br>Atmosphere: Hydrogen (96%), Helium (3%)<br>Avg. Temp: -178°C<br>Fact: Famous for its beautiful rings.`,
  uranus: `🔵 <b>Uranus</b><br>Diameter: 50,724 km<br>Orbit Speed: 6.8 km/s<br>Distance: 2.87B km<br>Moons: 27<br>Gravity: 8.69 m/s²<br>Length of Day: 17.2 hours<br>Length of Year: 84 years<br>Atmosphere: Hydrogen, Helium, Methane<br>Avg. Temp: -216°C<br>Fact: Rotates sideways.`,
  neptune: `🔵 <b>Neptune</b><br>Diameter: 49,244 km<br>Orbit Speed: 5.43 km/s<br>Distance: 4.5B km<br>Moons: 14<br>Gravity: 11.15 m/s²<br>Length of Day: 16.1 hours<br>Length of Year: 165 years<br>Atmosphere: Hydrogen, Helium, Methane<br>Avg. Temp: -214°C<br>Fact: Strongest winds in the solar system.`
};
